import turtle

turtle.hideturtle()
turtle.pensize(10)
turtle.speed(10)
turtle.penup()
turtle.goto(-150, 0)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(50)
turtle.penup()
turtle.goto(-30, 0)
turtle.pendown()
turtle.pencolor("black")
turtle.circle(50)
turtle.penup()
turtle.goto(90, 0)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(50)
turtle.penup()
turtle.goto(30, -55)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(50)
turtle.penup()
turtle.goto(-90, -55)
turtle.pendown()
turtle.pencolor("Yellow")
turtle.circle(50)
